apiVersion: v1
kind: service
metadata:
  name: my-app-service
  labels:
    author: intelliq
spec:
  type: nodeport
  port:
    port: 80
    targetport: 80
    nodeport: 30008
  selector:
    app: myapp
    author: intelliq
